version: "3.9"
services:
  nginx:
    image: jonasal/nginx-certbot:latest
    container_name: nginx
    env_file:
      - ./nginx-files/nginx-certbot.env
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ./nginx-files:/etc/nginx/user_conf.d
      - nginx_secrets:/etc/letsencrypt
    restart: always
  database:
    image: postgres:16
    container_name: database
    expose:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
      # - ./init.sh:/docker-entrypoint-initdb.d/init.sh
    deploy:
      resources:
        limits:
          memory: 500M
          ######################### CRLW #########################################
  crlw-app-backend:
    image: ladymeek/crlw-backend-do:sha-b2a5725
    container_name: crlw_api
    # build: ./backend
    expose:
      - "8000"
    restart: always
    depends_on:
      - "database"
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

    volumes:
      - ./local_settings_crlw.py:/user/src/app/drf_jwt_backend/local_settings.py
  crlw-app-frontend:
    image: ladymeek/crlw-frontend-do:sha-db7bcac
    container_name: crlw_frontend
    # build: ./frontend
    expose:
      - "80"
    depends_on:
      - "crlw-app-backend"
    restart: always
    ######################### CRLW #########################################
    ######################### MRS #########################################
  mrs-app-backend:
    image: ladymeek/tlb-backend-do:sha-4e4f07f
    container_name: mrs_api
    # build: ./backend
    expose:
      - "8000"
    restart: always
    depends_on:
      - "database"
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate --fake-initial && python manage.py runserver 0.0.0.0:8000"

    volumes:
      - ./local_settings_mrs.py:/user/src/app/drf_jwt_backend/local_settings.py
  mrs-app-frontend:
    image: ladymeek/tlb-frontend-do:sha-3a243e4
    container_name: mrs_frontend
    # build: ./frontend
    expose:
      - "80"
    depends_on:
      - "mrs-app-backend"
    restart: always
volumes:
  db-data:
  nginx_secrets:
